# -*- coding: utf-8 -*-
"""NETS 213 Final Project QC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DnKRwcU_jflvhvC8qmf2dPHjrgVU_4S7
"""

import pandas as pd

def majority_vote(data, hit_number):
  data = data.sort_values(by=['Destination'], ignore_index = True)
  # results will only include locations that were upvoted sufficiently
  results = []
  hit = 0
  while hit in range(len(data['Do you recommend visiting?'])):
    yes_count = 0
    for _ in range(hit_number):
      if (data['Do you recommend visiting?'][hit] == 'Yes'):
        if (data['Which best represents your relation to the destination'][hit]
            == 'I have been there'):
          yes_count = yes_count + 2
        else:
          yes_count = yes_count + 1
      hit = hit + 1
    if (yes_count >= hit_number):
      results.append((data['Destination'][hit - 1], True))
    else:
      results.append((data['Destination'][hit - 1], False))
  return results

def main():
  data = pd.read_csv('Aggregation Sample Input.csv')
  updated_destinations = majority_vote(data, 2)
  updated_df = pd.DataFrame(updated_destinations, columns = ['Destination', 'Recommend?'])
  updated_df.to_csv('new_destinations.csv')
if __name__ == '__main__':
    main()
  # With the new csv, we have a new (smaller) dataset for either further upvoting or refining