# -*- coding: utf-8 -*-
"""NETS 213 Final Project QC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DnKRwcU_jflvhvC8qmf2dPHjrgVU_4S7
"""

import pandas as pd

def majority_vote(data, hit_number):
  data = data.sort_values(by=['Destination'], ignore_index = True)
  # results will only include locations that were upvoted sufficiently
  results = []
  hit = 0
  while hit in range(len(data['Do you recommend visiting?'])):
    yes_been_count = 0
    yes_not_count = 0
    no_been_count = 0
    no_not_count = 0
    for _ in range(hit_number):
      if (data['Do you recommend visiting?'][hit] == 'Yes'):
        if (data['Which best represents your relation to the destination'][hit]
            == 'I have been there'):
          yes_been_count = yes_been_count + 1
        else:
          yes_not_count = yes_not_count + 1
      else:
        if (data['Which best represents your relation to the destination'][hit]
            == 'I have been there'):
          no_been_count = no_been_count + 1
        else:
          no_not_count = no_not_count + 1
      hit = hit + 1
    results.append((data['Destination'][hit - 1], yes_been_count, yes_not_count, no_been_count, no_not_count))
  return results

def main():
  data = pd.read_csv('qc_sample_input.csv')
  updated_destinations = majority_vote(data, 2)
  updated_df = pd.DataFrame(updated_destinations, columns = ['Destination', 'Yes Votes/Have gone',
                                                             'Yes Votes/Have not gone', 'No Votes/Have gone', 'No Votes/Have not gone'])
  updated_df.to_csv('new_destinations.csv')
if __name__ == '__main__':
    main()
  # With the new csv, we have a new (smaller) dataset for either further upvoting or refining